version: '3.3'

services:
  mongo:
    image: mongo:4.4
    ports:
      - 27017:27017
    volumes:
      - ./db:/data/db
    networks:
      - tracking

  minio:
    image: quay.io/minio/minio
    volumes:
      - ./minio:/data
    ports:
      - '80:9000'
      - '9001:9001'
    environment:
      - MINIO_ROOT_USER=console
      - MINIO_ROOT_PASSWORD=Zinza@2021
    command: server /data --console-address ":9001"
    restart: always

networks:
  tracking:
    driver: bridge
